// Approved by Tucker in tucker-event-review-2026-09-28.json.
// 36 upcoming occurrences; 7 past occurrences excluded. Source URLs retained for audit.
export const approvedEvents20260928 = [
  {
    "title": "newbie's Night",
    "description": "newbie's Night at Club Privata. Ages 21+ with valid ID. Membership: not required. Single Women: *Free Entry*; Couples: $40.00; Single Men: $50.00. Last entry 12:30am. - Last entry 12:30am. Venue dress code and waiver apply.",
    "venueName": "Club Privata",
    "address": "824 SW 1st Ave, Portland, OR 97204",
    "neighborhood": null,
    "lat": 45.516644,
    "lng": -122.6740564,
    "dateStart": "2026-10-01T20:00",
    "dateEnd": "2026-10-02T02:00",
    "dayOfWeek": "THU",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://www.clubprivata.com/events-2/newbies-night-dec",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://cdn.prod.website-files.com/5712b98b1b6331b5777255e5/6a8213c60f31dc656de00b60_October%20Socials2.png",
    "eventPageUrl": "https://www.clubprivata.com/events-2/newbies-night-dec",
    "sourceUrl": "https://www.clubprivata.com/events-2/newbies-night-dec",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "newbie's Night",
    "description": "newbie's Night at Club Privata. Ages 21+ with valid ID. Membership: not required. Single Women: *Free Entry*; Couples: $75.00; Single Men: $90.00. Last entry 1:30am. - Last entry 12:30am. Venue dress code and waiver apply.",
    "venueName": "Club Privata",
    "address": "824 SW 1st Ave, Portland, OR 97204",
    "neighborhood": null,
    "lat": 45.516644,
    "lng": -122.6740564,
    "dateStart": "2026-10-16T20:00",
    "dateEnd": "2026-10-17T03:00",
    "dayOfWeek": "FRI",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://www.clubprivata.com/events-2/newbies-night-oct2",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://cdn.prod.website-files.com/5712b98b1b6331b5777255e5/6a82164484c3f3b8a2a0f4f3_October%20Socials9.png",
    "eventPageUrl": "https://www.clubprivata.com/events-2/newbies-night-oct2",
    "sourceUrl": "https://www.clubprivata.com/events-2/newbies-night-oct2",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "newbie's Night",
    "description": "newbie's Night at Club Privata. Ages 21+ with valid ID. Membership: not required. Single Women: *Free Entry*; Couples: $40.00; Single Men: $50.00. Last entry 12:30am. - Last entry 12:30am. Venue dress code and waiver apply.",
    "venueName": "Club Privata",
    "address": "824 SW 1st Ave, Portland, OR 97204",
    "neighborhood": null,
    "lat": 45.516644,
    "lng": -122.6740564,
    "dateStart": "2026-11-05T20:00",
    "dateEnd": "2026-11-06T02:00",
    "dayOfWeek": "THU",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://www.clubprivata.com/events-2/newbies-night-nov",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://cdn.prod.website-files.com/5712b98b1b6331b5777255e5/6ab0b95466afe9ca53af59a4_November%20Socials2.png",
    "eventPageUrl": "https://www.clubprivata.com/events-2/newbies-night-nov",
    "sourceUrl": "https://www.clubprivata.com/events-2/newbies-night-nov",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "newbie's Night",
    "description": "newbie's Night at Club Privata. Ages 21+ with valid ID. Membership: not required. Single Women: *Free Entry*; Couples: $75.00; Single Men: $90.00. Last entry 1:30am. Venue dress code and waiver apply.",
    "venueName": "Club Privata",
    "address": "824 SW 1st Ave, Portland, OR 97204",
    "neighborhood": null,
    "lat": 45.516644,
    "lng": -122.6740564,
    "dateStart": "2026-11-20T20:00",
    "dateEnd": "2026-11-21T03:00",
    "dayOfWeek": "FRI",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://www.clubprivata.com/events-2/newbies-night-nov2",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://cdn.prod.website-files.com/5712b98b1b6331b5777255e5/6ab0bbf724518d9807c16346_November%20Socials9.png",
    "eventPageUrl": "https://www.clubprivata.com/events-2/newbies-night-nov2",
    "sourceUrl": "https://www.clubprivata.com/events-2/newbies-night-nov2",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "Stilettos & Stockings",
    "description": "Stilettos & Stockings at Club Privata. Ages 21+ with valid ID. Membership: required. Single Women: $15.00; Couples: $75.00; Single Man: $90.00. Last entry 1:30am. Venue dress code and waiver apply.",
    "venueName": "Club Privata",
    "address": "824 SW 1st Ave, Portland, OR 97204",
    "neighborhood": null,
    "lat": 45.516644,
    "lng": -122.6740564,
    "dateStart": "2026-10-02T20:00",
    "dateEnd": "2026-10-03T03:00",
    "dayOfWeek": "FRI",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://www.clubprivata.com/events-2/stilettos-stockings",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://cdn.prod.website-files.com/5712b98b1b6331b5777255e5/6a82143e0090a05089ec5308_October%20Socials3.png",
    "eventPageUrl": "https://www.clubprivata.com/events-2/stilettos-stockings",
    "sourceUrl": "https://www.clubprivata.com/events-2/stilettos-stockings",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "NEWBIE NIGHT PINEAPPLE PLAY PARTY!",
    "description": "NEWBIE NIGHT PINEAPPLE PLAY PARTY! at The Velvet Rope. Ages 21+ with valid ID. Membership or one-night guest membership required; venue waiver and dress code apply. Door Fees: Member Couples $50 Member Single Female $10 Member Single Males $55 One-Night Passes also available at the door!",
    "venueName": "The Velvet Rope",
    "address": "3533 SE Cesar E. Chavez Blvd, Portland, OR",
    "neighborhood": null,
    "lat": 45.496696557615,
    "lng": -122.622840610623,
    "dateStart": "2026-10-02T20:00",
    "dateEnd": "2026-10-03T03:00",
    "dayOfWeek": "FRI",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "DOOR_FEE",
    "ticketUrl": "https://velvetropepdx.com/event/10-2-2026/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://velvetropepdx.com/wp-content/uploads/2026/08/2.png",
    "eventPageUrl": "https://velvetropepdx.com/event/10-2-2026/",
    "sourceUrl": "https://velvetropepdx.com/event/10-2-2026/",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "Pink Ribbon",
    "description": "Pink Ribbon at Club Privata. Ages 21+ with valid ID. Membership: required. Single Women: $20.00; Couples: $100.00; Single Man: $120.00. Last entry 1:30am. Venue dress code and waiver apply.",
    "venueName": "Club Privata",
    "address": "824 SW 1st Ave, Portland, OR 97204",
    "neighborhood": null,
    "lat": 45.516644,
    "lng": -122.6740564,
    "dateStart": "2026-10-03T20:00",
    "dateEnd": "2026-10-04T03:00",
    "dayOfWeek": "SAT",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://www.clubprivata.com/events-2/pink-ribbon",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://cdn.prod.website-files.com/5712b98b1b6331b5777255e5/6a8214947ca92ce1cfc41432_October%20Socials4.png",
    "eventPageUrl": "https://www.clubprivata.com/events-2/pink-ribbon",
    "sourceUrl": "https://www.clubprivata.com/events-2/pink-ribbon",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "GLOW NIGHT!",
    "description": "GLOW NIGHT! at The Velvet Rope. Ages 21+ with valid ID. Membership or one-night guest membership required; venue waiver and dress code apply. Door Fees: Member Couples $60 Member Single Ladies $15 Member Single Males $65 One-Night Passes also available!",
    "venueName": "The Velvet Rope",
    "address": "3533 SE Cesar E. Chavez Blvd, Portland, OR",
    "neighborhood": null,
    "lat": 45.496696557615,
    "lng": -122.622840610623,
    "dateStart": "2026-10-03T20:00",
    "dateEnd": "2026-10-04T03:00",
    "dayOfWeek": "SAT",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "DOOR_FEE",
    "ticketUrl": "https://velvetropepdx.com/event/10-03-2026/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://velvetropepdx.com/wp-content/uploads/2026/08/4.png",
    "eventPageUrl": "https://velvetropepdx.com/event/10-03-2026/",
    "sourceUrl": "https://velvetropepdx.com/event/10-03-2026/",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "SLUT IT UP SUNDAY",
    "description": "SLUT IT UP SUNDAY at The Velvet Rope. Ages 21+ with valid ID. Membership or one-night guest membership required; venue waiver and dress code apply. Door Fees: Member Couples $35 Member Single Ladies $5 Member Single Gents $40 One-Night Passes also available!",
    "venueName": "The Velvet Rope",
    "address": "3533 SE Cesar E. Chavez Blvd, Portland, OR",
    "neighborhood": null,
    "lat": 45.496696557615,
    "lng": -122.622840610623,
    "dateStart": "2026-10-04T20:00",
    "dateEnd": "2026-10-05T02:00",
    "dayOfWeek": "SUN",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "DOOR_FEE",
    "ticketUrl": "https://velvetropepdx.com/event/10-04-2026/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://velvetropepdx.com/wp-content/uploads/2026/08/6.png",
    "eventPageUrl": "https://velvetropepdx.com/event/10-04-2026/",
    "sourceUrl": "https://velvetropepdx.com/event/10-04-2026/",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "Threesome thursday",
    "description": "Threesome thursday at Club Privata. Ages 21+ with valid ID. Membership: required. Single Women: *Free Entry*; Couples: $40.00; Couples & Single Woman: $40.00; Couples & Single Man: $75.00; Single Men: $50.00. Last entry 12:30am. Venue dress code and waiver apply.",
    "venueName": "Club Privata",
    "address": "824 SW 1st Ave, Portland, OR 97204",
    "neighborhood": null,
    "lat": 45.516644,
    "lng": -122.6740564,
    "dateStart": "2026-10-08T20:00",
    "dateEnd": "2026-10-09T02:00",
    "dayOfWeek": "THU",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://www.clubprivata.com/events-2/threesome-thursday",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://cdn.prod.website-files.com/5712b98b1b6331b5777255e5/6a8214f448a7ec3ac9ce16e9_October%20Socials5.png",
    "eventPageUrl": "https://www.clubprivata.com/events-2/threesome-thursday",
    "sourceUrl": "https://www.clubprivata.com/events-2/threesome-thursday",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "Ladies Night Out",
    "description": "Ladies Night Out at Club Privata. Ages 21+ with valid ID. Membership: required. Couples: $75.00; Single Man: $90.00. Last entry 1:30am. Venue dress code and waiver apply.",
    "venueName": "Club Privata",
    "address": "824 SW 1st Ave, Portland, OR 97204",
    "neighborhood": null,
    "lat": 45.516644,
    "lng": -122.6740564,
    "dateStart": "2026-10-09T20:00",
    "dateEnd": "2026-10-10T03:00",
    "dayOfWeek": "FRI",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://www.clubprivata.com/events-2/ladies-night-out",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://cdn.prod.website-files.com/5712b98b1b6331b5777255e5/6a82155b0f31dc656de04a93_October%20Socials6.png",
    "eventPageUrl": "https://www.clubprivata.com/events-2/ladies-night-out",
    "sourceUrl": "https://www.clubprivata.com/events-2/ladies-night-out",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "DEVILS UNDRESS – 2 for 1 Weekend!",
    "description": "DEVILS UNDRESS – 2 for 1 Weekend! at The Velvet Rope. Ages 21+ with valid ID. Membership or one-night guest membership required; venue waiver and dress code apply. Door Fees: Member Couples $60* Member Single Ladies $15* Member Single Males $65* One-Night Passes also available! *BOGO pricing applies for members in before 10pm. *Not yet a member? Sign up before 10PM tonight and get Saturday FREE",
    "venueName": "The Velvet Rope",
    "address": "3533 SE Cesar E. Chavez Blvd, Portland, OR",
    "neighborhood": null,
    "lat": 45.496696557615,
    "lng": -122.622840610623,
    "dateStart": "2026-10-09T20:00",
    "dateEnd": "2026-10-10T03:00",
    "dayOfWeek": "FRI",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "DOOR_FEE",
    "ticketUrl": "https://velvetropepdx.com/event/10-9-2026/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://velvetropepdx.com/wp-content/uploads/2026/08/TVR-OCTOBER-FLYER-2026-2.png",
    "eventPageUrl": "https://velvetropepdx.com/event/10-9-2026/",
    "sourceUrl": "https://velvetropepdx.com/event/10-9-2026/",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "FALL MASQUERADE",
    "description": "FALL MASQUERADE at The Velvet Rope. Ages 21+ with valid ID. No membership required for this open-house event; venue waiver and dress code apply. Door Fees: Member Couples $60 Member Single Ladies $15 Member Single Males $65 One-Night Passes also available!",
    "venueName": "The Velvet Rope",
    "address": "3533 SE Cesar E. Chavez Blvd, Portland, OR",
    "neighborhood": null,
    "lat": 45.496696557615,
    "lng": -122.622840610623,
    "dateStart": "2026-10-10T20:00",
    "dateEnd": "2026-10-11T03:00",
    "dayOfWeek": "SAT",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "DOOR_FEE",
    "ticketUrl": "https://velvetropepdx.com/event/10-10-2026/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://velvetropepdx.com/wp-content/uploads/2026/08/13.png",
    "eventPageUrl": "https://velvetropepdx.com/event/10-10-2026/",
    "sourceUrl": "https://velvetropepdx.com/event/10-10-2026/",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "OPEN HOUSE  –  NO MEMBERSHIP REQUIRED",
    "description": "OPEN HOUSE  –  NO MEMBERSHIP REQUIRED at The Velvet Rope. Ages 21+ with valid ID. No membership required for this open-house event; venue waiver and dress code apply. Door Fees: Member Couples $35 Member Single Ladies $5 Member Single Gents $40 One-Night Passes also available!",
    "venueName": "The Velvet Rope",
    "address": "3533 SE Cesar E. Chavez Blvd, Portland, OR",
    "neighborhood": null,
    "lat": 45.496696557615,
    "lng": -122.622840610623,
    "dateStart": "2026-10-11T20:00",
    "dateEnd": "2026-10-12T02:00",
    "dayOfWeek": "SUN",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "DOOR_FEE",
    "ticketUrl": "https://velvetropepdx.com/event/10-11-2026/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://velvetropepdx.com/wp-content/uploads/2026/08/14.png",
    "eventPageUrl": "https://velvetropepdx.com/event/10-11-2026/",
    "sourceUrl": "https://velvetropepdx.com/event/10-11-2026/",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "DEVIANCE!",
    "description": "DEVIANCE! at Club Privata. Ages 21+ with valid ID. Membership: included in $25 entry. Entry: $25.00. Last entry 12:30am. Venue dress code and waiver apply.",
    "venueName": "Club Privata",
    "address": "824 SW 1st Ave, Portland, OR 97204",
    "neighborhood": null,
    "lat": 45.516644,
    "lng": -122.6740564,
    "dateStart": "2026-10-15T20:00",
    "dateEnd": "2026-10-16T02:00",
    "dayOfWeek": "THU",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://www.clubprivata.com/events-2/deviance-oct",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://cdn.prod.website-files.com/5712b98b1b6331b5777255e5/6a8215ec2cd3d9bcbe4a5503_October%20Socials8.png",
    "eventPageUrl": "https://www.clubprivata.com/events-2/deviance-oct",
    "sourceUrl": "https://www.clubprivata.com/events-2/deviance-oct",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "DEVIANCE!",
    "description": "DEVIANCE! at Club Privata. Ages 21+ with valid ID. Membership: included in $25 entry. Entry: $25.00. Last entry 12:30am. Venue dress code and waiver apply.",
    "venueName": "Club Privata",
    "address": "824 SW 1st Ave, Portland, OR 97204",
    "neighborhood": null,
    "lat": 45.516644,
    "lng": -122.6740564,
    "dateStart": "2026-11-19T20:00",
    "dateEnd": "2026-11-20T02:00",
    "dayOfWeek": "THU",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://www.clubprivata.com/events-2/deviance-nov",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://cdn.prod.website-files.com/5712b98b1b6331b5777255e5/6ab0bb96de3e5e56a94c837b_November%20Socials8.png",
    "eventPageUrl": "https://www.clubprivata.com/events-2/deviance-nov",
    "sourceUrl": "https://www.clubprivata.com/events-2/deviance-nov",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "SAINTS & SINNERS",
    "description": "SAINTS & SINNERS at The Velvet Rope. Ages 21+ with valid ID. No membership required for this open-house event; venue waiver and dress code apply. Door Fees: Member Couples $50 Member Single Female $10 Member Single Males $55 One-Night Passes also available!",
    "venueName": "The Velvet Rope",
    "address": "3533 SE Cesar E. Chavez Blvd, Portland, OR",
    "neighborhood": null,
    "lat": 45.496696557615,
    "lng": -122.622840610623,
    "dateStart": "2026-10-16T20:00",
    "dateEnd": "2026-10-17T03:00",
    "dayOfWeek": "FRI",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "DOOR_FEE",
    "ticketUrl": "https://velvetropepdx.com/event/10-16-2026/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://velvetropepdx.com/wp-content/uploads/2026/08/16-1.png",
    "eventPageUrl": "https://velvetropepdx.com/event/10-16-2026/",
    "sourceUrl": "https://velvetropepdx.com/event/10-16-2026/",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "COUNTRY GRIND",
    "description": "COUNTRY GRIND at The Velvet Rope. Ages 21+ with valid ID. Membership or one-night guest membership required; venue waiver and dress code apply. Door Fees: Member Couples $60 Member Single Ladies $15 Member Single Males $65 One-Night Passes also available!",
    "venueName": "The Velvet Rope",
    "address": "3533 SE Cesar E. Chavez Blvd, Portland, OR",
    "neighborhood": null,
    "lat": 45.496696557615,
    "lng": -122.622840610623,
    "dateStart": "2026-10-17T20:00",
    "dateEnd": "2026-10-18T03:00",
    "dayOfWeek": "SAT",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "DOOR_FEE",
    "ticketUrl": "https://velvetropepdx.com/event/10-17-2026/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://velvetropepdx.com/wp-content/uploads/2026/08/21-1.png",
    "eventPageUrl": "https://velvetropepdx.com/event/10-17-2026/",
    "sourceUrl": "https://velvetropepdx.com/event/10-17-2026/",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "HAPPY HOUR HOOK-UP PARTY PLUS NAUGHTY KARAOKE!",
    "description": "HAPPY HOUR HOOK-UP PARTY PLUS NAUGHTY KARAOKE! at The Velvet Rope. Ages 21+ with valid ID. Membership or one-night guest membership required; venue waiver and dress code apply. Door Fees: Member Couples $35 Member Single Ladies $5 Member Single Gents $40 One-Night Passes also available!",
    "venueName": "The Velvet Rope",
    "address": "3533 SE Cesar E. Chavez Blvd, Portland, OR",
    "neighborhood": null,
    "lat": 45.496696557615,
    "lng": -122.622840610623,
    "dateStart": "2026-10-18T20:00",
    "dateEnd": "2026-10-19T02:00",
    "dayOfWeek": "SUN",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "DOOR_FEE",
    "ticketUrl": "https://velvetropepdx.com/event/10-18-2026/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://velvetropepdx.com/wp-content/uploads/2026/08/24.png",
    "eventPageUrl": "https://velvetropepdx.com/event/10-18-2026/",
    "sourceUrl": "https://velvetropepdx.com/event/10-18-2026/",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "RED LIGHT GREEN LIGHT PLAY PARTY!",
    "description": "RED LIGHT GREEN LIGHT PLAY PARTY! at The Velvet Rope. Ages 21+ with valid ID. Membership or one-night guest membership required; venue waiver and dress code apply. Door Fees: Member Couples $50 Member Single Female $10 Member Single Males $55 One-Night Passes also available!",
    "venueName": "The Velvet Rope",
    "address": "3533 SE Cesar E. Chavez Blvd, Portland, OR",
    "neighborhood": null,
    "lat": 45.496696557615,
    "lng": -122.622840610623,
    "dateStart": "2026-10-23T20:00",
    "dateEnd": "2026-10-24T03:00",
    "dayOfWeek": "FRI",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "DOOR_FEE",
    "ticketUrl": "https://velvetropepdx.com/event/10-23-2026/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://velvetropepdx.com/wp-content/uploads/2026/08/25.png",
    "eventPageUrl": "https://velvetropepdx.com/event/10-23-2026/",
    "sourceUrl": "https://velvetropepdx.com/event/10-23-2026/",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "DEAD MAN’S PARTY – KINK NIGHT",
    "description": "DEAD MAN’S PARTY – KINK NIGHT at The Velvet Rope. Ages 21+ with valid ID. Membership or one-night guest membership required; venue waiver and dress code apply. Door Fees: Member Couples $60 Member Single Ladies $15 Member Single Males $65 One-Night Passes also available!",
    "venueName": "The Velvet Rope",
    "address": "3533 SE Cesar E. Chavez Blvd, Portland, OR",
    "neighborhood": null,
    "lat": 45.496696557615,
    "lng": -122.622840610623,
    "dateStart": "2026-10-24T20:00",
    "dateEnd": "2026-10-25T03:00",
    "dayOfWeek": "SAT",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "DOOR_FEE",
    "ticketUrl": "https://velvetropepdx.com/event/10-24-2026/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://velvetropepdx.com/wp-content/uploads/2026/08/28.png",
    "eventPageUrl": "https://velvetropepdx.com/event/10-24-2026/",
    "sourceUrl": "https://velvetropepdx.com/event/10-24-2026/",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "ROSE CITY GANGBANG!",
    "description": "ROSE CITY GANGBANG! at The Velvet Rope. Ages 21+ with valid ID. Membership or one-night guest membership required; venue waiver and dress code apply. Door Fees: Member Couples $35 Member Single Ladies Free Member Single Gents $50 One-Night Pass Couples $55 One-Night Pass Single Ladies $10 One-Night Pass Single Gents $70",
    "venueName": "The Velvet Rope",
    "address": "3533 SE Cesar E. Chavez Blvd, Portland, OR",
    "neighborhood": null,
    "lat": 45.496696557615,
    "lng": -122.622840610623,
    "dateStart": "2026-10-25T20:00",
    "dateEnd": "2026-10-26T02:00",
    "dayOfWeek": "SUN",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "DOOR_FEE",
    "ticketUrl": "https://velvetropepdx.com/event/10-25-2026/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://velvetropepdx.com/wp-content/uploads/2026/08/29-1.png",
    "eventPageUrl": "https://velvetropepdx.com/event/10-25-2026/",
    "sourceUrl": "https://velvetropepdx.com/event/10-25-2026/",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "Costumes, Cocktails, & Contests",
    "description": "Costumes, Cocktails, & Contests at Club Privata. Ages 21+ with valid ID. Membership: included in the door price for this party. Single Women: $25.00; Couples: $75.00; Single Man: $85.00. Last entry 12:30am. Venue dress code and waiver apply.",
    "venueName": "Club Privata",
    "address": "824 SW 1st Ave, Portland, OR 97204",
    "neighborhood": null,
    "lat": 45.516644,
    "lng": -122.6740564,
    "dateStart": "2026-10-29T20:00",
    "dateEnd": "2026-10-30T02:00",
    "dayOfWeek": "THU",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://www.clubprivata.com/events-2/costumes-cocktails-contests",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://cdn.prod.website-files.com/5712b98b1b6331b5777255e5/6a8218f516fa97f5ffc18fa3_October%20Socials14.png",
    "eventPageUrl": "https://www.clubprivata.com/events-2/costumes-cocktails-contests",
    "sourceUrl": "https://www.clubprivata.com/events-2/costumes-cocktails-contests",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "HALLOWEEN OPEN HOUSE",
    "description": "HALLOWEEN OPEN HOUSE at The Velvet Rope. Ages 21+ with valid ID. No membership required for this open-house event; venue waiver and dress code apply. See the official event page for door pricing.",
    "venueName": "The Velvet Rope",
    "address": "3533 SE Cesar E. Chavez Blvd, Portland, OR",
    "neighborhood": null,
    "lat": 45.496696557615,
    "lng": -122.622840610623,
    "dateStart": "2026-10-30T20:00",
    "dateEnd": "2026-10-31T03:00",
    "dayOfWeek": "FRI",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://velvetropepdx.com/event/10-30-2026/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://velvetropepdx.com/wp-content/uploads/2026/08/34.png",
    "eventPageUrl": "https://velvetropepdx.com/event/10-30-2026/",
    "sourceUrl": "https://velvetropepdx.com/event/10-30-2026/",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "Masquerade of the Damned",
    "description": "Masquerade of the Damned at Club Privata. Ages 21+ with valid ID. Membership: included in the door price for this party. Single Women: $70.00; Couples: $240.00; Single Man: $250.00. Last entry 1:30am. The only way to guarantee entry is to pre-purchase a ticket online. This event will sell out.. Venue dress code and waiver apply.",
    "venueName": "Club Privata",
    "address": "824 SW 1st Ave, Portland, OR 97204",
    "neighborhood": null,
    "lat": 45.516644,
    "lng": -122.6740564,
    "dateStart": "2026-10-31T20:00",
    "dateEnd": "2026-11-01T02:00",
    "dayOfWeek": "SAT",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://www.clubprivata.com/events-2/masquerade-of-the-damned",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://cdn.prod.website-files.com/5712b98b1b6331b5777255e5/6a821a8da5af034799b75350_October%20Socials16.png",
    "eventPageUrl": "https://www.clubprivata.com/events-2/masquerade-of-the-damned",
    "sourceUrl": "https://www.clubprivata.com/events-2/masquerade-of-the-damned",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "THEE BIGGEST FUCKING HALLOWEEN PARTY",
    "description": "THEE BIGGEST FUCKING HALLOWEEN PARTY at The Velvet Rope. Ages 21+ with valid ID. Membership or one-night guest membership required; venue waiver and dress code apply. See the official event page for door pricing.",
    "venueName": "The Velvet Rope",
    "address": "3533 SE Cesar E. Chavez Blvd, Portland, OR",
    "neighborhood": null,
    "lat": 45.496696557615,
    "lng": -122.622840610623,
    "dateStart": "2026-10-31T20:00",
    "dateEnd": "2026-11-01T03:00",
    "dayOfWeek": "SAT",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://velvetropepdx.com/event/10-31-2026/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://velvetropepdx.com/wp-content/uploads/2026/08/39_20260919_202207_0038.png",
    "eventPageUrl": "https://velvetropepdx.com/event/10-31-2026/",
    "sourceUrl": "https://velvetropepdx.com/event/10-31-2026/",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "FANGBANG",
    "description": "FANGBANG at The Velvet Rope. Ages 21+ with valid ID. Membership or one-night guest membership required; venue waiver and dress code apply. See the official event page for door pricing.",
    "venueName": "The Velvet Rope",
    "address": "3533 SE Cesar E. Chavez Blvd, Portland, OR",
    "neighborhood": null,
    "lat": 45.496696557615,
    "lng": -122.622840610623,
    "dateStart": "2026-11-01T20:00",
    "dateEnd": "2026-11-02T02:00",
    "dayOfWeek": "SUN",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://velvetropepdx.com/event/11-1-2026/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://velvetropepdx.com/wp-content/uploads/2026/09/41.png",
    "eventPageUrl": "https://velvetropepdx.com/event/11-1-2026/",
    "sourceUrl": "https://velvetropepdx.com/event/11-1-2026/",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "Gang Bang",
    "description": "Gang Bang at Club Privata. Ages 21+ with valid ID. Membership: required. Single Women: Free; Couples: $40.00; Single Men: $50.00. Last entry 12:30am. - We reserve the right to limit the ratio of single men. - The only way to guarantee entry as a single man is to pre-purchase a ticket online. Venue dress code and waiver apply.",
    "venueName": "Club Privata",
    "address": "824 SW 1st Ave, Portland, OR 97204",
    "neighborhood": null,
    "lat": 45.516644,
    "lng": -122.6740564,
    "dateStart": "2026-11-12T20:00",
    "dateEnd": "2026-11-13T02:00",
    "dayOfWeek": "THU",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://www.clubprivata.com/events-2/gang-bang",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://cdn.prod.website-files.com/5712b98b1b6331b5777255e5/6ab0ba80bdd7e3517def22b3_November%20Socials5.png",
    "eventPageUrl": "https://www.clubprivata.com/events-2/gang-bang",
    "sourceUrl": "https://www.clubprivata.com/events-2/gang-bang",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "BETTY: A Queer Dance Party (HALLOWEEN EDITION) – 21+",
    "description": "BETTY Halloween queer dance party with dance and techno music, including DJ Sanro. Doors at 9pm. Listed ticket price $26.85.",
    "venueName": "Holocene",
    "address": "1001 SE Morrison, Portland, ",
    "neighborhood": null,
    "lat": 45.517263828809,
    "lng": -122.65558925207,
    "dateStart": "2026-10-31T21:00",
    "dateEnd": "",
    "dayOfWeek": "SAT",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://www.holocene.org/event/betty-a-queer-dance-party-halloween-edition-21-2/holocene/portland/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": false,
    "nudityOk": false,
    "posterImageUrl": "https://www.holocene.org/wp-content/uploads/2026/08/betty-a-queer-dance-party-halloween-edition-21.jpeg",
    "eventPageUrl": "https://www.holocene.org/event/betty-a-queer-dance-party-halloween-edition-21-2/holocene/portland/",
    "sourceUrl": "https://www.holocene.org/event/betty-a-queer-dance-party-halloween-edition-21-2/holocene/portland/",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "Amtrac @ PROCESS – 21+",
    "description": "Amtrac at Process, presented by Holocene and Spend the Night. Doors at 9pm. Venue confirmed in the event description: Process, not Holocene.",
    "venueName": "Process",
    "address": "5040 SE Milwaukie Ave, Portland, OR 97202",
    "neighborhood": null,
    "lat": 45.486159708058,
    "lng": -122.649861068595,
    "dateStart": "2026-11-19T21:00",
    "dateEnd": "",
    "dayOfWeek": "THU",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://www.holocene.org/event/amtrac-process-21/holocene/portland/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": false,
    "nudityOk": false,
    "posterImageUrl": "https://www.holocene.org/wp-content/uploads/2026/08/amtrac-process-21-1.jpeg",
    "eventPageUrl": "https://www.holocene.org/event/amtrac-process-21/holocene/portland/",
    "sourceUrl": "https://www.holocene.org/event/amtrac-process-21/holocene/portland/",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "Lez Out: Dykes Inferno",
    "description": "Lez Out Halloween party with DJs Mas O Menos and bb fat, drag hosted by Harlow Quinzel with Chatty Cathyter and Lavish Volt, and go-go dancers. Trans- and BIPOC-inclusive. General admission $10; community tickets $5.",
    "venueName": "White Owl Social Club",
    "address": "1305 Southeast 8th Avenue, Portland, OR, 97214",
    "neighborhood": null,
    "lat": 45.5134484,
    "lng": -122.6579941,
    "dateStart": "2026-10-17T21:00",
    "dateEnd": "",
    "dayOfWeek": "SAT",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://sickening.events/e/lez-out-dykes-inferno",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": false,
    "nudityOk": false,
    "posterImageUrl": "https://res.cloudinary.com/eventservice/image/upload/q_auto,f_auto/v1789685438/saas/logos/image_1789685433058_0rc7irvq3.webp",
    "eventPageUrl": "https://sickening.events/e/lez-out-dykes-inferno",
    "sourceUrl": "https://sickening.events/e/lez-out-dykes-inferno",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "Double XX Bear Dance",
    "description": "Bear-community dance night at CC Slaughters. Bears, cubs, otters, admirers and friends welcome. Ages 21+.",
    "venueName": "CC Slaughters",
    "address": "219 NW Davis St",
    "neighborhood": null,
    "lat": 45.524612586064,
    "lng": -122.67265978363,
    "dateStart": "2026-10-30T21:00",
    "dateEnd": "2026-10-31T02:00",
    "dayOfWeek": "FRI",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "UNKNOWN",
    "ticketUrl": "https://ccslaughterspdx.com/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": false,
    "nudityOk": false,
    "posterImageUrl": "https://ccslaughterspdx.com/wp-content/uploads/2026/07/DOUBLE_XX_BEAR_CALANDER_ONLINE.png",
    "eventPageUrl": "https://ccslaughterspdx.com/",
    "sourceUrl": "https://ccslaughterspdx.com/",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "Double XX Bear Dance — Hibernation Party",
    "description": "Bear-community dance night at CC Slaughters. Bears, cubs, otters, admirers and friends welcome. Ages 21+.",
    "venueName": "CC Slaughters",
    "address": "219 NW Davis St",
    "neighborhood": null,
    "lat": 45.524612586064,
    "lng": -122.67265978363,
    "dateStart": "2026-11-28T21:00",
    "dateEnd": "2026-11-29T02:00",
    "dayOfWeek": "SAT",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "UNKNOWN",
    "ticketUrl": "https://ccslaughterspdx.com/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": false,
    "nudityOk": false,
    "posterImageUrl": "https://ccslaughterspdx.com/wp-content/uploads/2026/07/DOUBLE_XX_BEAR_CALANDER_ONLINE.png",
    "eventPageUrl": "https://ccslaughterspdx.com/",
    "sourceUrl": "https://ccslaughterspdx.com/",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "CumUnion Portland",
    "description": "CumUnion Portland at Steam Portland, a private men's social club and bathhouse. Ages 18+ with valid government ID. Active membership required; event and locker or room charges apply. See the venue's current rates.",
    "venueName": "Steam Portland",
    "address": "2885 NE Sandy Blvd, Portland, OR 97232",
    "neighborhood": null,
    "lat": 45.529740871515,
    "lng": -122.635809981186,
    "dateStart": "2026-10-10T22:00",
    "dateEnd": "2026-10-11T04:00",
    "dayOfWeek": "SAT",
    "ageRequirement": "18_PLUS",
    "eventTypes": "[]",
    "admission": "DOOR_FEE",
    "ticketUrl": "https://www.cumunion.com/?page_id=13400",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://quillfish-bison-dpbr.squarespace.com/s/CUMUNION",
    "eventPageUrl": "https://www.cumunion.com/?page_id=13400",
    "sourceUrl": "https://www.cumunion.com/?page_id=13400",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "CumUnion Portland",
    "description": "CumUnion Portland at Steam Portland, a private men's social club and bathhouse. Ages 18+ with valid government ID. Active membership required; event and locker or room charges apply. See the venue's current rates.",
    "venueName": "Steam Portland",
    "address": "2885 NE Sandy Blvd, Portland, OR 97232",
    "neighborhood": null,
    "lat": 45.529740871515,
    "lng": -122.635809981186,
    "dateStart": "2026-11-14T22:00",
    "dateEnd": "2026-11-15T04:00",
    "dayOfWeek": "SAT",
    "ageRequirement": "18_PLUS",
    "eventTypes": "[]",
    "admission": "DOOR_FEE",
    "ticketUrl": "https://www.cumunion.com/?page_id=13400",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://quillfish-bison-dpbr.squarespace.com/s/CUMUNION",
    "eventPageUrl": "https://www.cumunion.com/?page_id=13400",
    "sourceUrl": "https://www.cumunion.com/?page_id=13400",
    "parseSource": "html",
    "warnings": []
  },
  {
    "title": "CumUnion Portland",
    "description": "CumUnion Portland at Steam Portland, a private men's social club and bathhouse. Ages 18+ with valid government ID. Active membership required; event and locker or room charges apply. See the venue's current rates.",
    "venueName": "Steam Portland",
    "address": "2885 NE Sandy Blvd, Portland, OR 97232",
    "neighborhood": null,
    "lat": 45.529740871515,
    "lng": -122.635809981186,
    "dateStart": "2026-12-12T22:00",
    "dateEnd": "2026-12-13T04:00",
    "dayOfWeek": "SAT",
    "ageRequirement": "18_PLUS",
    "eventTypes": "[]",
    "admission": "DOOR_FEE",
    "ticketUrl": "https://www.cumunion.com/?page_id=13400",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": false,
    "posterImageUrl": "https://quillfish-bison-dpbr.squarespace.com/s/CUMUNION",
    "eventPageUrl": "https://www.cumunion.com/?page_id=13400",
    "sourceUrl": "https://www.cumunion.com/?page_id=13400",
    "parseSource": "html",
    "warnings": []
  }
];
