// Tucker approved all 11 groups on 2026-09-28. 17 listings including two festival ranges.
// Official source links retained; no inferred end times or prices. Null posters use weekday defaults.
export const discoveredQueerEvents20260928 = [
  {
    "title": "PDX Rated",
    "description": "Queer-inclusive BDSM and clothing-optional EDM dance party at Nova PDX. Ages 21+. Check the organizer for current admission and event rules.",
    "venueName": "Nova PDX",
    "address": "722 E Burnside St, Portland, OR 97214",
    "lat": 45.522864237377,
    "lng": -122.658404662953,
    "neighborhood": null,
    "dateStart": "2026-10-02T21:00",
    "dateEnd": "",
    "dayOfWeek": "FRI",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://novapdxevents.com/",
    "sourceUrl": "https://novapdxevents.com/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": true,
    "posterImageUrl": null
  },
  {
    "title": "PDX Rated",
    "description": "Queer-inclusive BDSM and clothing-optional EDM dance party at Nova PDX. Ages 21+. Check the organizer for current admission and event rules.",
    "venueName": "Nova PDX",
    "address": "722 E Burnside St, Portland, OR 97214",
    "lat": 45.522864237377,
    "lng": -122.658404662953,
    "neighborhood": null,
    "dateStart": "2026-11-06T21:00",
    "dateEnd": "",
    "dayOfWeek": "FRI",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://novapdxevents.com/",
    "sourceUrl": "https://novapdxevents.com/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": true,
    "posterImageUrl": null
  },
  {
    "title": "PDX Rated",
    "description": "Queer-inclusive BDSM and clothing-optional EDM dance party at Nova PDX. Ages 21+. Check the organizer for current admission and event rules.",
    "venueName": "Nova PDX",
    "address": "722 E Burnside St, Portland, OR 97214",
    "lat": 45.522864237377,
    "lng": -122.658404662953,
    "neighborhood": null,
    "dateStart": "2026-12-04T21:00",
    "dateEnd": "",
    "dayOfWeek": "FRI",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://novapdxevents.com/",
    "sourceUrl": "https://novapdxevents.com/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": true,
    "nudityOk": true,
    "posterImageUrl": null
  },
  {
    "title": "Dyke Nite",
    "description": "Dyke Nite at Nova PDX. Ages 21+. Admission price and end time have not been confirmed.",
    "venueName": "Nova PDX",
    "address": "722 E Burnside St, Portland, OR 97214",
    "lat": 45.522864237377,
    "lng": -122.658404662953,
    "neighborhood": null,
    "dateStart": "2026-10-03T21:00",
    "dateEnd": "",
    "dayOfWeek": "SAT",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "UNKNOWN",
    "ticketUrl": "https://novapdxevents.com/",
    "sourceUrl": "https://novapdxevents.com/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": false,
    "nudityOk": false,
    "posterImageUrl": null
  },
  {
    "title": "Dyke Nite",
    "description": "Dyke Nite at Nova PDX. Ages 21+. Admission price and end time have not been confirmed.",
    "venueName": "Nova PDX",
    "address": "722 E Burnside St, Portland, OR 97214",
    "lat": 45.522864237377,
    "lng": -122.658404662953,
    "neighborhood": null,
    "dateStart": "2026-11-07T21:00",
    "dateEnd": "",
    "dayOfWeek": "SAT",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "UNKNOWN",
    "ticketUrl": "https://novapdxevents.com/",
    "sourceUrl": "https://novapdxevents.com/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": false,
    "nudityOk": false,
    "posterImageUrl": null
  },
  {
    "title": "Witches Ball of the West",
    "description": "Witches Ball of the West at Nova PDX. Ages 21+. See the organizer for tickets and current details.",
    "venueName": "Nova PDX",
    "address": "722 E Burnside St, Portland, OR 97214",
    "lat": 45.522864237377,
    "lng": -122.658404662953,
    "neighborhood": null,
    "dateStart": "2026-10-17T19:00",
    "dateEnd": "",
    "dayOfWeek": "SAT",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://novapdxevents.com/",
    "sourceUrl": "https://novapdxevents.com/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": false,
    "nudityOk": false,
    "posterImageUrl": null
  },
  {
    "title": "Haunted Honey × Sapphic PDX",
    "description": "A sapphic Halloween party at Nova PDX from the co-creator of Let Her Cook. Ages 21+. See the organizer for tickets.",
    "venueName": "Nova PDX",
    "address": "722 E Burnside St, Portland, OR 97214",
    "lat": 45.522864237377,
    "lng": -122.658404662953,
    "neighborhood": null,
    "dateStart": "2026-10-23T21:00",
    "dateEnd": "",
    "dayOfWeek": "FRI",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://novapdxevents.com/",
    "sourceUrl": "https://novapdxevents.com/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": false,
    "nudityOk": false,
    "posterImageUrl": null
  },
  {
    "title": "Shock Show in Space",
    "description": "Sci-fi horror drag show hosted by XO Skeleton, featuring Portland drag performers. Doors 7 p.m.; show 8–10 p.m. Ages 21+. Listed admission $18.",
    "venueName": "Clinton Street Theater",
    "address": "2522 SE Clinton St, Portland, OR 97202",
    "lat": null,
    "lng": null,
    "neighborhood": null,
    "dateStart": "2026-10-02T20:00",
    "dateEnd": "2026-10-02T22:00",
    "dayOfWeek": "FRI",
    "ageRequirement": "21_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://cstpdx.com/event/shock-show-in-space/",
    "sourceUrl": "https://cstpdx.com/event/shock-show-in-space/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": false,
    "nudityOk": false,
    "posterImageUrl": null
  },
  {
    "title": "Fright Night: A Halloween Circus",
    "description": "Night Flight presents a queer circus spoof of The Phantom of the Opera, featuring Jack StockLynn of Sir Cupcake’s Queer Circus. Doors one hour before the show. Rated PG-13 by the organizer; minors must be accompanied by a parent or guardian.",
    "venueName": "Alberta Rose Theatre",
    "address": "3000 NE Alberta St, Portland, OR 97211",
    "lat": 45.558981232861,
    "lng": -122.63477668578,
    "neighborhood": null,
    "dateStart": "2026-10-22T19:30",
    "dateEnd": "",
    "dayOfWeek": "THU",
    "ageRequirement": "UNVERIFIED",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://albertarosetheatre.com/calendar/category/series/night-flights-2026-fright-night-a-halloween-circus/alberta-rose-theatre/portland-oregon/",
    "sourceUrl": "https://albertarosetheatre.com/calendar/category/series/night-flights-2026-fright-night-a-halloween-circus/alberta-rose-theatre/portland-oregon/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": false,
    "nudityOk": false,
    "posterImageUrl": null
  },
  {
    "title": "Fright Night: A Halloween Circus",
    "description": "Night Flight presents a queer circus spoof of The Phantom of the Opera, featuring Jack StockLynn of Sir Cupcake’s Queer Circus. Doors one hour before the show. Rated PG-13 by the organizer; minors must be accompanied by a parent or guardian.",
    "venueName": "Alberta Rose Theatre",
    "address": "3000 NE Alberta St, Portland, OR 97211",
    "lat": 45.558981232861,
    "lng": -122.63477668578,
    "neighborhood": null,
    "dateStart": "2026-10-23T19:30",
    "dateEnd": "",
    "dayOfWeek": "FRI",
    "ageRequirement": "UNVERIFIED",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://albertarosetheatre.com/calendar/category/series/night-flights-2026-fright-night-a-halloween-circus/alberta-rose-theatre/portland-oregon/",
    "sourceUrl": "https://albertarosetheatre.com/calendar/category/series/night-flights-2026-fright-night-a-halloween-circus/alberta-rose-theatre/portland-oregon/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": false,
    "nudityOk": false,
    "posterImageUrl": null
  },
  {
    "title": "Fright Night: A Halloween Circus",
    "description": "Night Flight presents a queer circus spoof of The Phantom of the Opera, featuring Jack StockLynn of Sir Cupcake’s Queer Circus. Doors one hour before the show. Rated PG-13 by the organizer; minors must be accompanied by a parent or guardian.",
    "venueName": "Alberta Rose Theatre",
    "address": "3000 NE Alberta St, Portland, OR 97211",
    "lat": 45.558981232861,
    "lng": -122.63477668578,
    "neighborhood": null,
    "dateStart": "2026-10-24T19:30",
    "dateEnd": "",
    "dayOfWeek": "SAT",
    "ageRequirement": "UNVERIFIED",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://albertarosetheatre.com/calendar/category/series/night-flights-2026-fright-night-a-halloween-circus/alberta-rose-theatre/portland-oregon/",
    "sourceUrl": "https://albertarosetheatre.com/calendar/category/series/night-flights-2026-fright-night-a-halloween-circus/alberta-rose-theatre/portland-oregon/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": false,
    "nudityOk": false,
    "posterImageUrl": null
  },
  {
    "title": "Fright Night: A Halloween Circus",
    "description": "Night Flight presents a queer circus spoof of The Phantom of the Opera, featuring Jack StockLynn of Sir Cupcake’s Queer Circus. Doors one hour before the show. Rated PG-13 by the organizer; minors must be accompanied by a parent or guardian.",
    "venueName": "Alberta Rose Theatre",
    "address": "3000 NE Alberta St, Portland, OR 97211",
    "lat": 45.558981232861,
    "lng": -122.63477668578,
    "neighborhood": null,
    "dateStart": "2026-10-25T18:30",
    "dateEnd": "",
    "dayOfWeek": "SUN",
    "ageRequirement": "UNVERIFIED",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://albertarosetheatre.com/calendar/category/series/night-flights-2026-fright-night-a-halloween-circus/alberta-rose-theatre/portland-oregon/",
    "sourceUrl": "https://albertarosetheatre.com/calendar/category/series/night-flights-2026-fright-night-a-halloween-circus/alberta-rose-theatre/portland-oregon/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": false,
    "nudityOk": false,
    "posterImageUrl": null
  },
  {
    "title": "Dapperlesque: A Gender-Bending Burlesque Cabaret",
    "description": "An evening of gender-bending burlesque and drag presented by Lacy Productions. Doors 7 p.m.; show 8 p.m. See the organizer for the current program, tickets, and admission policy.",
    "venueName": "Alberta Rose Theatre",
    "address": "3000 NE Alberta St, Portland, OR 97211",
    "lat": 45.558981232861,
    "lng": -122.63477668578,
    "neighborhood": null,
    "dateStart": "2026-10-29T20:00",
    "dateEnd": "",
    "dayOfWeek": "THU",
    "ageRequirement": "UNVERIFIED",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://www.dapperlesque.com/",
    "sourceUrl": "https://www.dapperlesque.com/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": false,
    "nudityOk": false,
    "posterImageUrl": null
  },
  {
    "title": "The Big Trans Comedy Show",
    "description": "Hear You Loud & Queer presents an all-trans stand-up lineup celebrating Trans Awareness Month, with proceeds benefiting SMYRC. Doors 7 p.m.; show 8 p.m. Ages 18+; ages 18–20 must be accompanied by a parent or guardian.",
    "venueName": "Alberta Rose Theatre",
    "address": "3000 NE Alberta St, Portland, OR 97211",
    "lat": 45.558981232861,
    "lng": -122.63477668578,
    "neighborhood": null,
    "dateStart": "2026-11-13T20:00",
    "dateEnd": "",
    "dayOfWeek": "FRI",
    "ageRequirement": "18_PLUS",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://albertarosetheatre.com/event/the-big-trans-comedy-show/alberta-rose-theatre/portland-oregon/",
    "sourceUrl": "https://albertarosetheatre.com/event/the-big-trans-comedy-show/alberta-rose-theatre/portland-oregon/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": false,
    "nudityOk": false,
    "posterImageUrl": null
  },
  {
    "title": "Mx. Dahlia Belle: Affirmed (A Live Comedy Taping)",
    "description": "A live comedy taping with trans comedian Mx. Dahlia Belle at Polaris Hall. Doors 6 p.m.; show 7 p.m. See the official ticket listing for admission and age requirements.",
    "venueName": "Polaris Hall",
    "address": "635 N Killingsworth Court, Portland, OR 97217",
    "lat": null,
    "lng": null,
    "neighborhood": null,
    "dateStart": "2026-11-22T19:00",
    "dateEnd": "",
    "dayOfWeek": "SUN",
    "ageRequirement": "UNVERIFIED",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://www.etix.com/ticket/p/36347493",
    "sourceUrl": "https://www.etix.com/ticket/p/36347493",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": false,
    "nudityOk": false,
    "posterImageUrl": null
  },
  {
    "title": "Stage Fright Festival",
    "description": "Queer horror theater festival, October 8–18. Opening preview and trivia: October 8 at 7:30 p.m. Closing Macabre Cabaret: October 18 at 7:30 p.m., lasting 90 minutes. Separate performances take place across the festival; this date range does not mean continuous opening hours. Consult the linked program for each performance, content rating, and ticket.",
    "venueName": "CoHo Theatre",
    "address": "2257 NW Raleigh St, Portland, OR 97210",
    "lat": null,
    "lng": null,
    "neighborhood": null,
    "dateStart": "2026-10-08T19:30",
    "dateEnd": "2026-10-18T21:00",
    "dayOfWeek": "THU",
    "ageRequirement": "UNVERIFIED",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://www.stagefrightfestival.com/2026-festival",
    "sourceUrl": "https://www.stagefrightfestival.com/2026-festival",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": false,
    "nudityOk": false,
    "posterImageUrl": null
  },
  {
    "title": "QDoc Film Festival",
    "description": "LGBTQ+ documentary festival at Cinema 21, October 23–25. Festival pass pickup reception is October 23, 5–6:30 p.m.; individual screening times vary. The organizer’s festival-pass listing gives an overall October 23 at 5 p.m. to October 25 at 10 p.m. window; this is not continuous screening or venue operating hours. Check the festival program for screening tickets and age guidance.",
    "venueName": "Cinema 21",
    "address": "616 NW 21st Ave, Portland, OR 97209",
    "lat": null,
    "lng": null,
    "neighborhood": null,
    "dateStart": "2026-10-23T17:00",
    "dateEnd": "2026-10-25T22:00",
    "dayOfWeek": "FRI",
    "ageRequirement": "UNVERIFIED",
    "eventTypes": "[]",
    "admission": "TICKETED",
    "ticketUrl": "https://qdocfilmfest.org/",
    "sourceUrl": "https://qdocfilmfest.org/",
    "isPublic": true,
    "isPrivate": false,
    "isHouseParty": false,
    "isSexPositive": false,
    "nudityOk": false,
    "posterImageUrl": null
  }
];
