import catalog from '../client/public/outzide-map/places.json';
export const closureSource='https://apps.fs.usda.gov/arcx/rest/services/EDW/EDW_RecreationOpportunities_01/MapServer/0';
export const normalizeName=(v:string)=>v.toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]/g,'');
export function closureState(raw:unknown){const s=String(raw||'').toLowerCase().trim();if(['closed for season','seasonally closed','seasonal closure'].includes(s))return 'seasonal';if(['closed','temporarily closed'].includes(s))return 'closed';if(s==='open')return 'open';return 'unknown';}
export function sourceId(p:{officialUrl?:string|null;url?:string|null}){try{const u=new URL(p.officialUrl||p.url||'');if(!/(^|\.)fs\.usda\.gov$/.test(u.hostname))return null;const id=u.searchParams.get('recid');return id&&/^\d+$/.test(id)?Number(id):null;}catch{return null;}}
export function matchStatuses(places:any[],features:any[],checkedAt:string){return places.flatMap(p=>{const id=sourceId(p),infra=/^usfs-([0-9.]+)$/.exec(p.id)?.[1];if(id===null&&!infra)return [];const rows=features.map(f=>f.attributes).filter(a=>a&&(a.recareaid===id||(infra&&a.infra_cn===infra))&&normalizeName(a.recareaname||'')===normalizeName(p.name));if(!rows.length)return [];const states=[...new Set(rows.map(a=>closureState(a.openstatus)))];const status=states.length===1?states[0]:'unknown';return [{placeId:p.id,status,reason:String(rows[0].openstatus||'Not reported'),sourceUrl:rows[0].recareaid===id?(p.officialUrl||p.url):closureSource+'/query?f=pjson&where=recareaid%3D'+rows[0].recareaid,checkedAt,sourceUpdatedAt:null}];});}
let cache:{checkedAt:string;statuses:any[]}|null=null;let pending:Promise<any>|null=null;
export async function getOutzClosures(){
 if(cache&&Date.now()-Date.parse(cache.checkedAt)<5*60_000)return cache;
 if(pending)return pending;
 pending=(async()=>{const ids=[...new Set(catalog.places.map(sourceId).filter(id=>id!==null))];const infra=catalog.places.map(p=>/^usfs-([0-9.]+)$/.exec(p.id)?.[1]).filter(Boolean);const features:any[]=[];
 for(let offset=0;offset<Math.max(ids.length,infra.length);offset+=60){const u=new URL(closureSource+'/query');u.search=new URLSearchParams({f:'json',where:[ids.slice(offset,offset+60).length?`recareaid IN (${ids.slice(offset,offset+60).join(',')})`:null,infra.slice(offset,offset+60).length?`infra_cn IN (${infra.slice(offset,offset+60).map(id=>"'"+id+"'").join(',')})`:null].filter(Boolean).join(' OR '),outFields:'recareaid,recareaname,openstatus,infra_cn',returnGeometry:'false'}).toString();const r=await fetch(u,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('Closure source unavailable');const data=await r.json();if(data.error||!Array.isArray(data.features)||data.exceededTransferLimit)throw Error('Incomplete closure source');features.push(...data.features);}
 const checkedAt=new Date().toISOString();cache={checkedAt,statuses:matchStatuses(catalog.places,features,checkedAt)};return cache;})().finally(()=>{pending=null;});return pending;
}
