import type { Express } from "express";
import { randomUUID, createHash } from "node:crypto";
import { sqlite } from "./storage";
import { ensureCommunityTables } from "./communities";
import { eventPath } from "@shared/eventSlug";
import { placePath } from "@shared/placeSlug";
import { PLATFORM_API_VERSION, parsePlatformId, platformId, platformListQuerySchema, platformObjectSchema, platformObjectTypes, platformSearchQuerySchema, type PlatformObjectType, type PlatformObject } from "@shared/platform";
import { platformOpenApi } from "./platformOpenApi";

const GUIDE_CATALOG = [
  { id: "access", name: "Access & Safety", summary: "Accessibility, privacy, and safety guidance for using Zaylist.", url: "/access" },
  { id: "nude-beaches-safety", name: "Nude Beaches Safety Guide", summary: "Safety guidance for Portland-area clothing-optional destinations.", url: "/nude-beaches/safety" },
] as const;
const ALLOWED_LIMITS = { default: 20, max: 100 };

function ensurePlatformTables() {
  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS platform_identities (
      typed_id TEXT PRIMARY KEY, resource_type TEXT NOT NULL, legacy_table TEXT NOT NULL,
      legacy_id TEXT NOT NULL, created_at TEXT NOT NULL,
      UNIQUE(resource_type, legacy_table, legacy_id)
    );
    CREATE INDEX IF NOT EXISTS idx_platform_identities_legacy ON platform_identities(resource_type,legacy_table,legacy_id);
    CREATE TABLE IF NOT EXISTS platform_relationships (
      id TEXT PRIMARY KEY, from_id TEXT NOT NULL, to_id TEXT NOT NULL,
      relationship_type TEXT NOT NULL, provenance TEXT NOT NULL DEFAULT 'platform',
      visibility TEXT NOT NULL DEFAULT 'public', created_at TEXT NOT NULL,
      UNIQUE(from_id,to_id,relationship_type)
    );
    CREATE INDEX IF NOT EXISTS idx_platform_relationships_from ON platform_relationships(from_id,relationship_type);
    CREATE INDEX IF NOT EXISTS idx_platform_relationships_to ON platform_relationships(to_id,relationship_type);
    CREATE TABLE IF NOT EXISTS platform_request_metrics (
      request_id TEXT PRIMARY KEY, method TEXT NOT NULL, path TEXT NOT NULL,
      status INTEGER NOT NULL, latency_ms INTEGER NOT NULL, user_id INTEGER,
      created_at TEXT NOT NULL
    );
  `);
}
function identityTable(type:PlatformObjectType){return type==="event"?"events":type==="community"?"communities":type==="listing"?"sellz_posts":type==="gig"?"gig_posts":type==="place"||type==="organization"?"businesses":type==="profile"?"users":type==="guide"?"guide_catalog":"media_catalog";}
function assignedId(type:PlatformObjectType,legacyId:string|number,preferred?:string){const table=identityTable(type),key=String(legacyId);const found=sqlite.prepare("SELECT typed_id FROM platform_identities WHERE resource_type=? AND legacy_table=? AND legacy_id=?").get(type,table,key) as any;if(found)return String(found.typed_id);const generated=preferred||platformId(type,randomUUID().replace(/-/g,""));sqlite.prepare("INSERT OR IGNORE INTO platform_identities (typed_id,resource_type,legacy_table,legacy_id,created_at) VALUES (?,?,?,?,?)").run(generated,type,table,key,new Date().toISOString());return String((sqlite.prepare("SELECT typed_id FROM platform_identities WHERE resource_type=? AND legacy_table=? AND legacy_id=?").get(type,table,key) as any).typed_id);}
function identityRecord(id:string){return sqlite.prepare("SELECT * FROM platform_identities WHERE typed_id=?").get(id) as any;}
function backfillPlatformIdentities(){const sources:Array<[PlatformObjectType,string]>=[["event","events"],["community","communities"],["listing","sellz_posts"],["gig","gig_posts"],["place","businesses"],["profile","users"],["organization","businesses"]];sqlite.transaction(()=>{for(const[type,table]of sources)for(const row of sqlite.prepare(`SELECT id FROM ${table}`).all() as any[])assignedId(type,row.id,type==="community"?String(row.id):undefined);for(const guide of GUIDE_CATALOG)assignedId("guide",guide.id,platformId("guide",guide.id));})();}
function syncPlatformRelationships(){const map:any={event:"event",sellz:"listing",gig:"gig",place:"place",guide:"guide"};const insert=sqlite.prepare("INSERT OR IGNORE INTO platform_relationships (id,from_id,to_id,relationship_type,provenance,visibility,created_at) VALUES (?,?,?,?,?,?,?)");sqlite.transaction(()=>{for(const row of sqlite.prepare("SELECT community_id,target_type,target_id,relationship_type,created_at FROM community_relationships").all() as any[]){const type=map[row.target_type] as PlatformObjectType|undefined;if(!type)continue;const from=assignedId("community",row.community_id,String(row.community_id)),to=assignedId(type,row.target_id),key=createHash("sha256").update(`${from}:${to}:${row.relationship_type}`).digest("hex").slice(0,24);insert.run(`rel_${key}`,from,to,row.relationship_type,"community_relationships","public",row.created_at||new Date().toISOString());}})();}

function requestId(req: any) { return String(req.get?.("x-request-id") || randomUUID()).slice(0, 100); }
function envelope(req: any, data: unknown, meta?: Record<string, unknown>) { return { apiVersion: PLATFORM_API_VERSION, requestId: requestId(req), data, ...(meta ? { meta } : {}) }; }
function failure(req: any, res: any, status: number, code: string, message: string, details?: unknown) { return res.status(status).json({ apiVersion: PLATFORM_API_VERSION, requestId: requestId(req), error: { code, message, status, ...(details === undefined ? {} : { details }) } }); }
function limitOf(value: unknown) { const parsed = Number(value); return Number.isInteger(parsed) && parsed > 0 ? Math.min(parsed, ALLOWED_LIMITS.max) : ALLOWED_LIMITS.default; }
function cursorEncode(value: string | number) { return Buffer.from(String(value), "utf8").toString("base64url"); }
function cursorDecode(value: unknown) { try { return value ? Buffer.from(String(value), "base64url").toString("utf8") : null; } catch { return null; } }
function safePhotos(value:unknown){try{const parsed=JSON.parse(String(value||"[]"));return Array.isArray(parsed)?parsed:[];}catch{return [];}}
function readCaps(type: PlatformObjectType, sourceId: string | number, userId?: number) {
  const caps = ["read"];
  if (type === "community" && userId) {
    const id = String(sourceId);
    const row = sqlite.prepare("SELECT role,status FROM community_memberships WHERE community_id=? AND user_id=?").get(id, userId) as any;
    if (row?.status === "active") caps.push("community.leave", "community.post.create");
    if (row?.status === "active" && ["owner", "moderator"].includes(row.role)) caps.push("community.manage", "community.moderate", "relationship.manage");
    if (row?.status === "active" && row.role === "owner") caps.push("community.ownership.transfer", "community.moderator.assign");
  }
  return caps;
}
function base(type: PlatformObjectType, sourceId: string | number, row: any, req: any) {
  return { id: assignedId(type, sourceId, type === "community" ? String(sourceId) : undefined), type, name: String(row.name || row.title || row.username || "Untitled"), summary: row.summary ?? row.description ?? null, url: String(row.url || "/"), imageUrl: row.imageUrl ?? row.image_url ?? null, visibility: row.visibility || "public", status: String(row.status || "active").toLowerCase(), sourceId, createdAt: row.createdAt ?? row.created_at ?? null, updatedAt: row.updatedAt ?? row.updated_at ?? row.createdAt ?? row.created_at ?? null, capabilities: readCaps(type, sourceId, req.session?.userId) };
}

function eventObject(row:any,req:any):PlatformObject { return {...base("event",row.id,{...row,name:row.title,url:eventPath(row.id,row.title,row.day_of_week),imageUrl:row.poster_image_url,status:row.status},req),type:"event",startsAt:row.date_start,endsAt:row.date_end,venueName:row.venue_name,neighborhood:row.neighborhood||null} as PlatformObject; }
function communityObject(row:any,req:any):PlatformObject { const membership=req.session?.userId?sqlite.prepare("SELECT role,status FROM community_memberships WHERE community_id=? AND user_id=?").get(row.id,req.session.userId) as any:null;const count=sqlite.prepare("SELECT COUNT(*) count FROM community_memberships WHERE community_id=? AND status='active'").get(row.id) as any;return {...base("community",row.id,{...row,url:`/z/${row.slug}`,imageUrl:row.image_url,status:"active",visibility:row.visibility==="private"?"private":row.visibility},req),type:"community",slug:row.slug,memberCount:Number(count?.count||0),membershipPolicy:row.membership_policy,viewerRole:membership?.status==="active"?membership.role:null} as PlatformObject; }
function listingObject(row:any,req:any):PlatformObject { return {...base("listing",row.id,{...row,name:row.title,url:`/sellz?post=${row.id}`,imageUrl:safePhotos(row.photo_urls)[0]||null},req),type:"listing",priceCents:Number(row.price_cents),neighborhood:row.neighborhood||null,category:row.category} as PlatformObject; }
function gigObject(row:any,req:any):PlatformObject { return {...base("gig",row.id,{...row,name:row.title,url:`/pride-work?post=${row.id}`,imageUrl:row.image_url},req),type:"gig",postType:row.post_type,location:row.location||null,compensation:row.compensation||null} as PlatformObject; }
function placeObject(row:any,req:any):PlatformObject { return {...base("place",row.id,{...row,url:placePath(row.id,row.name),imageUrl:row.image_url,status:row.status},req),type:"place",placeType:row.place_type||row.type,neighborhood:row.neighborhood||null,address:row.address||null} as PlatformObject; }
function guideObject(row:any,req:any):PlatformObject { return {...base("guide",row.id,{...row,status:"published"},req),type:"guide",slug:row.id} as PlatformObject; }
function profileObject(row:any,req:any):PlatformObject { return {...base("profile",row.id,{...row,name:row.display_name||row.username,summary:null,url:`/u/${row.username}`,imageUrl:row.photo_url,status:"active"},req),type:"profile",username:row.username} as PlatformObject; }
function organizationObject(row:any,req:any):PlatformObject { return {...base("organization",row.id,{...row,url:placePath(row.id,row.name),imageUrl:row.image_url,status:row.status},req),type:"organization",organizationType:row.type,neighborhood:row.neighborhood||null} as PlatformObject; }
function mediaObjects(req:any):PlatformObject[]{ const out:PlatformObject[]=[];const add=(ownerType:PlatformObjectType,ownerId:any,url:any,name:any)=>{if(!url)return;const hash=createHash("sha256").update(`${ownerType}:${ownerId}:${url}`).digest("hex").slice(0,24);out.push({...base("media",hash,{name,summary:null,url:String(url),imageUrl:String(url),status:"active"},req),type:"media",mediaType:"image",ownerId:assignedId(ownerType,ownerId)} as PlatformObject)};(sqlite.prepare("SELECT id,title,poster_image_url FROM events WHERE status='LIVE' AND poster_image_url IS NOT NULL LIMIT 500").all() as any[]).forEach(r=>add("event",r.id,r.poster_image_url,`${r.title} poster`));(sqlite.prepare("SELECT id,name,image_url FROM businesses WHERE active=1 AND image_url IS NOT NULL LIMIT 500").all() as any[]).forEach(r=>add("place",r.id,r.image_url,`${r.name} image`));return out; }

function tableFor(type:PlatformObjectType){return type==="event"?"events":type==="community"?"communities":type==="listing"?"sellz_posts":type==="gig"?"gig_posts":type==="place"||type==="organization"?"businesses":type==="profile"?"users":null;}
function visibleWhere(type:PlatformObjectType){if(type==="event")return "status='LIVE'";if(type==="community")return "visibility IN ('public','discoverable')";if(type==="listing")return "status IN ('ACTIVE','RESERVED')";if(type==="gig")return "status='LIVE'";if(type==="place")return "active=1 AND COALESCE(status,'OPEN')!='CLOSED'";if(type==="organization")return "active=1 AND COALESCE(status,'OPEN')!='CLOSED' AND type IN ('group','nonprofit')";if(type==="profile")return "COALESCE(status,'active')='active'";return "1=1";}
function mapObject(type:PlatformObjectType,row:any,req:any){return type==="event"?eventObject(row,req):type==="community"?communityObject(row,req):type==="listing"?listingObject(row,req):type==="gig"?gigObject(row,req):type==="place"?placeObject(row,req):type==="guide"?guideObject(row,req):type==="profile"?profileObject(row,req):organizationObject(row,req);}
function listObjects(type:PlatformObjectType,req:any){const objects=type==="guide"?GUIDE_CATALOG.map(row=>guideObject(row,req)):type==="media"?mediaObjects(req):(sqlite.prepare(`SELECT * FROM ${tableFor(type)!} WHERE ${visibleWhere(type)} ORDER BY id`).all() as any[]).map(row=>mapObject(type,row,req));return objects.map(object=>platformObjectSchema.parse(object));}
function readableCommunity(sourceId:string,userId?:number){const id=sourceId.startsWith("com_")?sourceId:`com_${sourceId}`;const row=sqlite.prepare("SELECT visibility FROM communities WHERE id=?").get(id) as any;if(!row)return false;if(row.visibility!=="private")return true;if(!userId)return false;return Boolean(sqlite.prepare("SELECT 1 FROM community_memberships WHERE community_id=? AND user_id=? AND status='active'").get(id,userId));}
function getObject(id:string,req:any){const parsed=parsePlatformId(id),identity=identityRecord(id);if(!parsed||!identity||identity.resource_type!==parsed.type)return null;const source=String(identity.legacy_id);if(parsed.type==="guide")return GUIDE_CATALOG.find(g=>g.id===source)?guideObject(GUIDE_CATALOG.find(g=>g.id===source)!,req):null;if(parsed.type==="media")return mediaObjects(req).find(x=>x.id===id)||null;const table=tableFor(parsed.type);if(!table)return null;if(parsed.type==="community"&&!readableCommunity(source,req.session?.userId))return null;const key=parsed.type==="community"?source:Number.isFinite(Number(source))?Number(source):source;const row=sqlite.prepare(`SELECT * FROM ${table} WHERE id=? AND ${visibleWhere(parsed.type)}`).get(key) as any;return row?mapObject(parsed.type,row,req):null;}
function objectRelationships(object:PlatformObject,req:any){const rels:any[]=[],seen=new Set<string>();const add=(type:string,from:string,to:string,id?:string)=>{const key=`${type}:${from}:${to}`;if(seen.has(key)||!getObject(to,req))return;seen.add(key);rels.push({id:id||`rel_${createHash("sha256").update(key).digest("hex").slice(0,24)}`,type,from,to});};for(const row of sqlite.prepare("SELECT id,from_id,to_id,relationship_type FROM platform_relationships WHERE from_id=? ORDER BY created_at,id").all(object.id) as any[])add(row.relationship_type,row.from_id,row.to_id,row.id);if(object.type==="event"){const row=sqlite.prepare("SELECT id FROM businesses WHERE active=1 AND LOWER(name)=LOWER((SELECT venue_name FROM events WHERE id=?)) LIMIT 1").get(object.sourceId) as any;if(row)add("hosted_at",object.id,assignedId("place",row.id));}if(object.type==="listing"||object.type==="gig"){const table=object.type==="listing"?"sellz_posts":"gig_posts";const row=sqlite.prepare(`SELECT user_id FROM ${table} WHERE id=?`).get(object.sourceId) as any;if(row?.user_id)add("created_by",object.id,assignedId("profile",row.user_id));}if(object.type==="media")add("depicts",object.id,(object as any).ownerId);return rels;}

export function registerPlatformV1(app:Express){ensureCommunityTables();ensurePlatformTables();backfillPlatformIdentities();mediaObjects({session:{}});syncPlatformRelationships();app.use("/api/v1",(req:any,res,next)=>{if(process.env.PLATFORM_API_V1_ENABLED==="false")return failure(req,res,503,"API_DISABLED","Platform API v1 is temporarily disabled");const id=requestId(req),started=Date.now();res.setHeader("X-Request-Id",id);res.setHeader("X-Zaylist-API-Version",PLATFORM_API_VERSION);res.setHeader("Cache-Control",req.session?.userId?"private, no-store":"public, max-age=30");req.platformRequestId=id;res.on("finish",()=>{try{sqlite.prepare("INSERT OR REPLACE INTO platform_request_metrics (request_id,method,path,status,latency_ms,user_id,created_at) VALUES (?,?,?,?,?,?,?)").run(id,req.method,String(req.path).slice(0,240),res.statusCode,Date.now()-started,req.session?.userId||null,new Date().toISOString());}catch(error){console.error("[platform-v1-metrics]",error);}});next();});
  app.get("/api/v1",(req:any,res)=>res.json(envelope(req,{name:"Zaylist Platform API",version:PLATFORM_API_VERSION,objectTypes:platformObjectTypes,authentication:"Internal website sessions; public reads only",writes:"Product routes remain authoritative during migration",endpoints:["/api/v1/objects/:id","/api/v1/:type","/api/v1/search","/api/v1/relationships/:id","/api/v1/capabilities"]})));
  app.get("/api/v1/capabilities",(req:any,res)=>res.json(envelope(req,{authenticated:Boolean(req.session?.userId),capabilities:req.session?.userId?["platform.read","platform.search"]:["platform.read.public","platform.search.public"]})));
  app.get("/api/v1/openapi.json",(_req,res)=>res.json(platformOpenApi));
  app.get("/api/v1/search",(req:any,res)=>{const parsedQuery=platformSearchQuerySchema.safeParse(req.query);if(!parsedQuery.success)return failure(req,res,422,"VALIDATION_ERROR","Search query is invalid",parsedQuery.error.flatten());const q=parsedQuery.data.q,requested=String(parsedQuery.data.types||"").split(",").filter(Boolean);const types=(requested.length?requested:platformObjectTypes).filter((x):x is PlatformObjectType=>(platformObjectTypes as readonly string[]).includes(x));if(!types.length)return failure(req,res,400,"INVALID_TYPE","No valid object types requested");const needle=q.toLocaleLowerCase(),buckets=types.map(type=>listObjects(type,req).filter(item=>`${item.name} ${item.summary||""}`.toLocaleLowerCase().includes(needle))),all:PlatformObject[]=[];for(let index=0;buckets.some(bucket=>index<bucket.length);index++)for(const bucket of buckets)if(bucket[index])all.push(bucket[index]);const limit=limitOf(parsedQuery.data.limit),start=Number(cursorDecode(parsedQuery.data.cursor)||0),data=all.slice(start,start+limit),next=start+data.length<all.length?cursorEncode(start+data.length):null;res.json(envelope(req,data,{query:q,types,count:data.length,total:all.length,nextCursor:next,hasMore:Boolean(next)}));});
  app.get("/api/v1/objects/:id",(req:any,res)=>{const object=getObject(req.params.id,req);if(!object)return failure(req,res,404,"OBJECT_NOT_FOUND","Object not found");res.json(envelope(req,object));});
  app.get("/api/v1/objects/:id/capabilities",(req:any,res)=>{const object=getObject(req.params.id,req);if(!object)return failure(req,res,404,"OBJECT_NOT_FOUND","Object not found");res.json(envelope(req,{objectId:object.id,allowed:object.capabilities}));});
  app.get("/api/v1/relationships/:id",(req:any,res)=>{const object=getObject(req.params.id,req);if(!object)return failure(req,res,404,"OBJECT_NOT_FOUND","Object not found");res.json(envelope(req,objectRelationships(object,req),{objectId:object.id}));});
  app.get("/api/v1/:type/:id",(req:any,res)=>{const aliases:any={events:"event",communities:"community",listings:"listing",gigs:"gig",places:"place",guides:"guide",profiles:"profile",organizations:"organization",media:"media"},expected=aliases[req.params.type] as PlatformObjectType|undefined;if(!expected)return failure(req,res,404,"RESOURCE_NOT_FOUND","Unknown API resource");const object=getObject(req.params.id,req);if(!object||object.type!==expected)return failure(req,res,404,"OBJECT_NOT_FOUND","Object not found");res.json(envelope(req,object));});
  app.get("/api/v1/:type",(req:any,res)=>{const parsedQuery=platformListQuerySchema.safeParse(req.query);if(!parsedQuery.success)return failure(req,res,422,"VALIDATION_ERROR","List query is invalid",parsedQuery.error.flatten());const singular=String(req.params.type).replace(/s$/,"");const aliases:any={events:"event",communities:"community",listings:"listing",gigs:"gig",places:"place",guides:"guide",profiles:"profile",organizations:"organization",media:"media"};const type=(aliases[req.params.type]||singular) as PlatformObjectType;if(!(platformObjectTypes as readonly string[]).includes(type))return failure(req,res,404,"RESOURCE_NOT_FOUND","Unknown API resource");const all=listObjects(type,req),limit=limitOf(parsedQuery.data.limit),start=Number(cursorDecode(parsedQuery.data.cursor)||0),data=all.slice(start,start+limit),next=start+data.length<all.length?cursorEncode(start+data.length):null;res.json(envelope(req,data,{type,count:data.length,total:all.length,nextCursor:next,hasMore:Boolean(next)}));});
}
