import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {PORTLAND_BUILDING_MODELS,parseBuildingGlb,replacementBuildingSurfaces,BUILDING_MODEL_MIN_ZOOM} from '../client/public/zaydar-map/building-models.js';
const parse=m=>{const b=fs.readFileSync(new URL(m.url));return parseBuildingGlb(b.buffer.slice(b.byteOffset,b.byteOffset+b.length),m)};
test('all eight supplied models keep filename GPS, authored meter height and finite grounded geometry',()=>{const heights=[163.38,43.3,65,38,18,72.75,32.6,49];assert.equal(PORTLAND_BUILDING_MODELS.length,8);PORTLAND_BUILDING_MODELS.forEach((m,i)=>{const p=parse(m),match=m.url.match(/_lat([\d.]+)_lon(-[\d.]+)_/);assert.deepEqual(m.center,[+match[2],+match[1]]);assert.ok(Math.abs(p.bounds.max[2]-heights[i])<.02);assert.equal(p.bounds.min[2],0);assert.ok(p.vertices.every(Number.isFinite));assert.ok(p.count<100000);for(let j=3;j<p.vertices.length;j+=7)assert.ok(Math.abs(Math.hypot(...p.vertices.slice(j,j+3))-1)<.001);});assert.equal(BUILDING_MODEL_MIN_ZOOM,12);});
const square=(x,y,s=.00002)=>[[x-s,y-s],[x+s,y-s],[x+s,y+s],[x-s,y+s],[x-s,y-s]];
const model={center:[0,0],bearing:90,count:3,bounds:{min:[-10,-10,0],max:[10,10,20]},footprint:{min:[-10,-10],max:[10,10]}};
test('replacing one polygon preserves unrelated buildings sharing its vector-tile ID',()=>{const kept=square(.01,.01),f={id:12,properties:{render_height:25},geometry:{type:'MultiPolygon',coordinates:[[square(0,0)],[kept]]}};const out=replacementBuildingSurfaces([f],[model]);assert.deepEqual(out.ids,[12]);assert.equal(out.data.features.length,1);assert.deepEqual(out.data.features[0].geometry.coordinates,[kept]);assert.equal(out.data.features[0].properties.render_height,25);});
test('unloaded or failed assets keep their original buildings',()=>{const f={id:12,properties:{},geometry:{type:'Polygon',coordinates:[square(0,0)]}};assert.deepEqual(replacementBuildingSurfaces([f],[{...model,count:0}]).ids,[]);});
test('a long base building overlapping the model is removed even if its centroid lies outside',()=>{const f={id:12,properties:{},geometry:{type:'Polygon',coordinates:[[[0,0],[.001,0],[.001,.0001],[0,.0001],[0,0]]]}};assert.deepEqual(replacementBuildingSurfaces([f],[model]).ids,[12]);});
test('node translation, rotation, nonuniform scale and indexed vertex order are applied',()=>{
 const binary=Buffer.alloc(78);new Float32Array(binary.buffer,binary.byteOffset,18).set([0,0,0,1,0,0,0,1,0, 0,0,1,0,0,1,0,0,1]);binary.writeUInt16LE(2,72);binary.writeUInt16LE(0,74);binary.writeUInt16LE(1,76);
 const json={asset:{version:'2.0'},scene:0,scenes:[{nodes:[0]}],nodes:[{mesh:0,translation:[10,20,30],scale:[2,3,4],rotation:[0,0,Math.SQRT1_2,Math.SQRT1_2]}],meshes:[{primitives:[{attributes:{POSITION:0,NORMAL:1},indices:2}]}],buffers:[{byteLength:80}],bufferViews:[{buffer:0,byteOffset:0,byteLength:36},{buffer:0,byteOffset:36,byteLength:36},{buffer:0,byteOffset:72,byteLength:6}],accessors:[{bufferView:0,componentType:5126,count:3,type:'VEC3'},{bufferView:1,componentType:5126,count:3,type:'VEC3'},{bufferView:2,componentType:5123,count:3,type:'SCALAR'}]};
 const text=Buffer.from(JSON.stringify(json)),length=Math.ceil(text.length/4)*4,b=Buffer.alloc(12+8+length+8+80,32);b.writeUInt32LE(0x46546c67,0);b.writeUInt32LE(2,4);b.writeUInt32LE(b.length,8);b.writeUInt32LE(length,12);b.writeUInt32LE(0x4e4f534a,16);text.copy(b,20);b.writeUInt32LE(80,20+length);b.writeUInt32LE(0x004e4942,24+length);binary.copy(b,28+length);
 const parsed=parseBuildingGlb(b.buffer.slice(b.byteOffset,b.byteOffset+b.length),{bearing:90});assert.deepEqual([...parsed.vertices.slice(0,3)].map(Math.round),[7,30,0]);assert.deepEqual([...parsed.vertices.slice(7,10)].map(Math.round),[10,30,0]);assert.deepEqual([...parsed.vertices.slice(14,17)].map(Math.round),[10,30,2]);assert.ok(Math.abs(parsed.vertices[4]-1)<1e-6);
});
