/* The index. One entry per specimen; the page and the sidebar both read this.
   nav  = short sidebar label. t = full title in the caption.
   st   = shipped (default) | queued | draft.
   c    = component paths whose .d.ts feed the props table. */
window.DS_NS = "PDXPrideGuideDesignSystem_b20420";
window.DS_BANDS = [
{band:null, groups:[
  {n:"Read me", d:"What this system is, where the ground truth lives, the caveats, and how to ask for any of it.", items:[
    {rules:"handoff/Zaylist Rebrand Prompt.md", f:"guidelines/readme.html", w:980, h:2600, nav:"Read me", t:"Design system read me", s:"The whole written standard: sources, site map, content fundamentals, visual foundations, signature effects, page patterns, iconography, avatars, components, caveats and known code gaps."},
    {f:"guidelines/prompts.html", w:980, h:2400, nav:"Prompts", t:"Prompts", s:"How to ask for anything in this system, in the words the system already uses: the vocabulary index, say-this-not-that, six copyable prompt recipes, the guardrails worth repeating, and the difference between using the system and changing it."}]}]},

{band:"A · Language", c:"--neon-yellow", d:"The measurable layer. Everything downstream is assembled out of these four groups, so they come first.", groups:[
  {n:"Color", d:"Surfaces, the context primaries, the nine-stop spectrum, and the two colour systems that carry data rather than decoration.", items:[
    {f:"guidelines/color-surfaces.html", w:900, h:520, nav:"Surfaces & text", t:"Surfaces & text", s:"Near-black base, hard borders, warm text."},
    {f:"guidelines/color-primaries.html", w:1000, h:1000, nav:"Context primaries", t:"Context primaries", s:"Acid yellow is the default action colour, not the only one. Hub and settings are cyan, admin is magenta, the owner desk is violet, Rooster Rock is orange and Sauvie Island is acid green. One data-context attribute rebinds --accent and --c for a whole subtree.", st:"queued"},
    {f:"guidelines/color-neon.html", w:760, h:1500, nav:"Neon & spectrum", t:"Neon palette & spectrum", s:"One neon per element, yellow is primary, plus the nine-stop spectrum tape with hex, RGB and hue reference."},
    {f:"guidelines/color-days.html", w:900, h:430, nav:"Day colors", t:"Day colors", s:"Mon to Sun keys. Data, not decoration. Toggle calm mode in the sidebar to watch them flatten."},
    {f:"guidelines/color-boards.html", w:720, h:270, nav:"Board accents", t:"Community board accents", s:"One identity color per board, softened on utility surfaces."},
    {f:"guidelines/color-utility.html", w:880, h:560, nav:"Utility layer", t:"Utility layer", s:"Ink panels, mono kickers and the status ramp: the data-dense register."}]},
  {n:"Type & space", d:"Two families and a 4px grid. Both specimens read their numbers back from the token files at load.", items:[
    {f:"guidelines/type-body.html", w:880, h:1220, nav:"Type system", t:"Type system", s:"Barlow Condensed display, Inter body, mono utility, with the full display to meta scale."},
    {f:"guidelines/spacing.html", w:760, h:700, nav:"Spacing & radius", t:"Spacing & radius", s:"The 4px scale, semantic gaps and the radius ramp, each value read from tokens/layout.css when the page loads."}]},
  {n:"Voice", d:"How the system sounds. The third half of the language, and the one most often skipped.", items:[
    {f:"guidelines/copy-rules.html", w:1000, h:1500, nav:"Copy rules", t:"Copy rules", s:"The register with write-this and not-this, the name pun, scene vernacular, mantras, casing and the event line."}]},
  {n:"Icons", d:"One drawing standard, 32 glyphs.", items:[
    {f:"guidelines/icons.html", w:880, h:440, nav:"Line icon library", t:"Line icon library", s:"All 32 brand icons on a 24px grid, 2.2 stroke, round caps, spectrum-colored. Inherit currentColor when inlined."}]}]},

{band:"B · Brand", c:"--neon-cyan", d:"The parts that are Zaylist rather than good practice: the treatments, the written standard, and the app face.", groups:[
  {n:"Treatments", d:"The card shell every surface shares, plus the three effects that carry the brand without a logo in sight.", items:[
    {f:"guidelines/brand-bloom.html", w:900, h:900, nav:"Lit plate & bloom", t:"Lit plate & floor bloom", s:"The flat 4px magenta offset is retired. Posters, markers, tape and collage now read as a lit plate on a black keyline with the element's own accent blooming on the floor, the same idiom as the seam, chips and tags.", st:"queued"},
    {f:"guidelines/brand-motifs.html", w:700, h:300, nav:"Seam, markers & tags", t:"Seam, markers & tags", s:"Animated flowing seam (route loader), kicker chip, filled sticker tags.", st:"queued"},
    {f:"guidelines/title-motif.html", w:1000, h:2200, nav:"Title motif", t:"Title motif · Dynamic text", s:"HAÜSING name-over-cover: key terms, half vs Forming title frames (55×58 / 72×58), equal line heights, photo well is separate. Live: HousingWell.tsx."},
    {f:"guidelines/card-system.html", w:1180, h:4200, nav:"Card system", t:"Card system, deep glass", c:["data-display/EventCard","data-display/PosterCard","data-display/PlaceCard","data-display/StatCard"], s:"One shell drives Events, the Directory, the ads and every board. The accent contract, the anatomy layer by layer, the four surfaces, the modal as the open state of the same object, motion, and the token table. HAÜSING uses the same shell; its name-over-cover is the title motif panel."},
    {f:"guidelines/brand-glitch.html", w:900, h:820, nav:"Glitch", t:"Glitch", s:"The slow RGB glitch on the nav and hero wordmark: cycle, active window, offsets, ghost filters, and the off switch. Copyable markup and CSS."}]},
  {n:"Brand guide", d:"The written standard for everything that has no token: the mark, imagery, voice, accessibility, trademark.", items:[
    {f:"brand-guide/Zaylist Brand Guide v2.html", w:1180, h:1400, nav:"Brand guide", t:"Brand guide", s:"Thirteen sections: the mark, the city lockup, clear space, glow, monochrome, backgrounds, misuse, applications, essence, grid, imagery, voice, accessibility and trademark. Scroll inside the frame.", scroll:1}]},
  {n:"App face", d:"The one artifact with its own end-to-end package.", items:[
    {f:"app-face/App Face Standards.html", w:1180, h:2600, nav:"App Face Standards", t:"App Face Standards", s:"The spec, verbatim from the handoff package in app-face/. Anatomy, the six iOS appearances, the two web build paths, every shipped export, and the files themselves. Downloads are live."}]}]},

{band:"C · Surfaces", c:"--neon-magenta", d:"Everything you can put on a screen: the shared glass chassis, the components built on it, and how all of it moves.", groups:[
  {n:"Glass", d:"One token set drives every card, tile, inbox, map, row and nav surface in the system.", items:[
    {f:"guidelines/glass-cards.html", w:1200, h:1500, nav:"Glass surface system", t:"Glass surface system", s:"The source of truth: bevel, bloom, refract seam and the poster well, with every surface that inherits them."}]},
  {n:"Components", d:"Everything shipped as a React component, previewed from the compiled bundle. Each entry copies a working import line and expands its real props table, read live from the .d.ts.", items:[
    {jsx:"<Button accent=\"lime\" arrow>View as schedule</Button>\n<Button variant=\"solid\" accent=\"cyan\" size=\"sm\">RSVP</Button>\n<IconButton label=\"Filter\" icon={<FilterIcon />} />\n<SearchInput placeholder=\"Search events, places, people\" onChange={setQ} />\n<FilterChip active accent=\"magenta\">Tonight</FilterChip>", f:"components/forms/forms.card.html", w:700, h:520, nav:"Buttons & inputs", t:"Buttons, inputs & filters", s:"The home hero glass pill, neon CTAs, icon buttons, search, filter chips.", st:"queued", c:["forms/Button","forms/IconButton","forms/SearchInput","forms/FilterChip"]},
    {jsx:"<Badge accent=\"cyan\">Ticketed</Badge>\n<StatPill label=\"Going\" value={128} />\n<Countdown to=\"2026-07-16T18:00:00-07:00\" />\n<StickerBadge accent=\"yellow\">Free</StickerBadge>", f:"components/data-display/data-display.card.html", w:700, h:360, nav:"Badges & pills", t:"Badges, pills, countdown & stickers", s:"Labels, counts, the event countdown, slogan stickers.", st:"queued", c:["data-display/Badge","data-display/StatPill","data-display/Countdown","data-display/StickerBadge"]},
    {jsx:"<BoardCard board=\"spotted\" title=\"Blue jacket at Darcelle\" body={post.body} author={post.author} />\n<AdCard sponsor=\"Rooster Rock Farm Stand\" href=\"/go/rrfs\" />\n<FeedItem kind=\"rsvp\" author={user} event={event} at={ts} />", f:"components/data-display/board-ad-feed.card.html", w:900, h:620, nav:"Board, ad & feed", t:"Board, ad & feed cards", s:"Community board posts with motifs, affiliate ad slots, hub scene-feed items on glass.", c:["data-display/BoardCard","data-display/AdCard","data-display/FeedItem"]},
    {jsx:"<SectionHeader kicker=\"Up next\" title=\"Thursday\" accent=\"cyan\" />\n<Divider variant=\"rainbow\" />", f:"components/layout/layout.card.html", w:700, h:420, nav:"Headers & dividers", t:"Section headers & dividers", s:"Section openers and spectrum dividers.", c:["layout/SectionHeader","layout/Divider"]},
    {jsx:"<InfoTile accent=\"violet\" label=\"Venues\" value={42} note=\"Directory\" />\n<ActionRow n={1} title=\"Claim your venue\" href=\"/promoters/claim\" />\n<NavBar user={user} unread={3} onCalmToggle={toggleCalm} />", f:"components/layout/infra-action-nav.card.html", w:900, h:560, nav:"Infra & action rows", t:"Infra tiles, action rows & nav", s:"Left-accent infrastructure tiles, numbered promoter action rows, and the nav bar shell.", c:["layout/InfoTile","forms/ActionRow","layout/NavBar"]},
    {jsx:"<Avatar name=\"Tucker\" ring=\"progress\" size=\"lg\" />\n<Avatar name=\"Rowan\" ring=\"aromantic\" size=\"md\" />\n<Logo variant=\"lockup\" size={56} src=\"app-face/icons/zaylist-512.png\" />", f:"components/brand/avatars.card.html", w:700, h:420, nav:"Avatars & rings", t:"Avatars & identity rings", s:"Identity ring around the face, all eighteen from the live avatarRings.ts. Progress is the default.", c:["brand/Avatar","brand/Logo"]}
]},
  {n:"Motion", d:"How surfaces behave. Easings, durations, the signature keyframes, the wider ambient library, and calm mode over all of it.", items:[
    {f:"guidelines/motion.html", w:980, h:3400, nav:"Motion, loaders & seams", t:"Motion, loaders & seams", s:"Easings and durations, the seam engine and Seam Charge route loader, spectrum loaders, pull to refresh, entrances, ambient loops, the flag-ring bloom, the add-ons, and calm mode. Every pdx* keyframe here comes from tokens/effects.css; the page never redeclares one. The RSVP button in the sparks demo is the solid Button from 09.1, so this panel is queued with it.", st:"queued"},
    {f:"guidelines/motion-library.html", w:1000, h:2600, nav:"Motion library", t:"Motion library", s:"The fifteen ambient and surface motions outside the seam, loader and entrance sets: the two aurora layers, spectrum wave, divider flow, word glitch, sticker float, board flicker, schedule entrance, attendance pop, sheet up, inbox overlay, holo sheen, the hero parallax, the hero overlay videos and the generic parallax containers. Every card copies a Claude-ready rules block, or take all fifteen at once."}]}]},

{band:"D · Patterns", c:"--neon-orange", d:"Page-level surfaces that are composed rather than componentized. Bigger than a component, smaller than a page.", groups:[
  {n:"Nav bar", d:"Two navigation models: one header row on desktop, two bars on mobile that split identity from movement.", items:[
    {f:"guidelines/nav-desktop.html", w:1400, h:1500, nav:"Desktop", t:"Desktop nav", s:"The header row: wordmark, primary links with the Boards dropdown, Hub with its unread dot, the avatar menu, calm toggle, the signed-out Join button, and the seam. Ported from Nav.tsx and siteNav.ts. The Join button is drawn from the same chrome atoms as 09.1, so it is queued with the rest of the button work.", st:"queued"},
    {f:"guidelines/mobile-nav.html", w:900, h:2100, nav:"Mobile", t:"Mobile nav", s:"Both bars. Top: Home and About segmented pair, alert bolt, avatar cluster or Join. Bottom: the five-tab dock, every active accent, the two tab sheets, and the full spec."}]},
  {n:"Hub & feed", d:"The signed-in home: a three-column shell, five feed tabs, eleven card kinds.", items:[
    {f:"guidelines/hub-feed.html", w:1100, h:2100, nav:"Hub shell & news feed", t:"Hub shell & news feed", s:"Rail sections and accents, the right rails, feed tabs and predicates, card kinds, card anatomy. Ported from hub/HubV2.tsx and shared/hubFeed.ts."}]},
  {n:"Floating inbox", d:"One overlay surface for everything, and it never navigates.", items:[
    {f:"guidelines/floating-inbox.html", w:1100, h:2400, nav:"Inbox, queue & desk", t:"Inbox, admin queue, owner desk & stats", s:"The navy-framed sheet and desktop button, every admin category with its endpoints, all six owner-desk kinds, the bar-chart stats, and the sheet palette. Ported from InboxOverlay.tsx and docs/floating-inbox.md. Queue actions now use the outline Button from 09.1, so they are queued with it.", st:"queued"}]},
  {n:"Maps", d:"Large enough to be its own pattern rather than a component: four map surfaces, every pin, and all the chrome.", items:[
    {jsx:"<MapPanel pins={pins} height={320} legend locate />\n<MapLegend cats={DIR_CATS} />", f:"components/map/map.card.html", w:900, h:2600, nav:"Map surfaces & pins", t:"Map surfaces & pins", s:"The Events board, the home strip, the Directory island and the two beaches, plus pins, the key, and all map chrome. Ported from ds/mapTheme.ts.", c:["map/MapPanel","map/MapLegend"]}]}]},

{band:"E · In use", c:"--day-mon-text", d:"The payoff. Everything above, assembled and working.", groups:[
  {n:"The live site", d:"Interactive. Click through it, then compare any surface against its specimen above.", items:[
    {f:"ui_kits/zaylist/index.html", w:1280, h:860, nav:"Full site", t:"Zaylist, full site", s:"Home, Events, Schedule, Directory, Hub and Admin.", scroll:1},
    {f:"ui_kits/zaylist/index.html#nudebeaches", w:1280, h:860, nav:"Nude Beaches", t:"Nude Beaches", s:"Rooster Rock and Collins Beach: live conditions band, refresh bar, map with the queer-corner legend, and the real trip logistics (fees, checklist, wildlife-area rules, farm stops).", scroll:1},
    {f:"ui_kits/zaylist/index.html#profile", w:1280, h:860, nav:"Public profile", t:"Public profile", s:"A member profile at /u/handle: hero, Followers / Hosting / Attended / Going strip, accent marquee, hosting rails, Top 8, The Big One, Going, Updates and the flyer stash.", scroll:1}]}]}
];
